ruby '1.9.3'
source 'http://rubygems.org'

gem "rails", "2.3.14"
gem "json"

group :development, :test do
  gem "sqlite3"
end

group :production do
  gem 'mysql2'
  gem 'activerecord-mysql2-adapter'
end
