<br /><br />
<div id="view-content">
	<p>View script for controller <b>Guestbook</b> and script/action name <b>sign</b></p>

    <!-- application/views/scripts/guestbook/sign.phtml -->
    Du bist der <?php 
    $defaultNamespace = new Zend_Session_Namespace('Default');
    echo $defaultNamespace->numberOfPageRequests; ?>-ste Besucher.<br/>
    Please use the form below to sign our guestbook!

    <?php
    $this->form->setAction($this->url());
    echo $this->form;
    ?>
</div>